### ISSUE TITLE
Improve Business features/User Story Template

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/accelerators#8]
**Description**
As a product owner
I want an improved user story/business feature template
so that I can quickly fill in user stories 

Improving the current story template to provide more value and minimize chaos. 

**Acceptance Criteria**
- [x] Granularity in stories

- [x] Research template examples/ideas

- [x] Find effective standardization methods

**Comment by debsmith-ux** [comment]
https://paladinarcher.sharepoint.com/:u:/g/EdIrOC7nZNhAngL_T0g9XLkBn21T1ebwKJ_hyLULkPgYlw

**Comment by debsmith-ux** [comment]
https://www.amazon.com/User-Story-Mapping-Discover-Product/dp/1491904909

**Comment by debsmith-ux** [comment]
[Backlog Refinement Facilitator Checklist.pdf](https://github.com/paladinarcher/accelerators/files/5533432/Backlog.Refinement.Facilitator.Checklist.pdf)

**Comment by debsmith-ux** [comment]
https://www.scaledagileframework.com/story/

**Comment by debsmith-ux** [comment]
Most stories emerge from business and enabler features in the Program Backlog, but others come from the team’s local context.

© Scaled Agile, Inc.
Include this copyright notice with the copied content.

Read the FAQs on how to use SAFe content and trademarks here:
https://www.scaledagile.com/about/about-us/permissions-faq/
Explore Training at:
https://www.scaledagile.com/training/calendar/

**Comment by debsmith-ux** [comment]
As a (user role), I want to (activity), so that (business value)

© Scaled Agile, Inc.
Include this copyright notice with the copied content.

Read the FAQs on how to use SAFe content and trademarks here:
https://www.scaledagile.com/about/about-us/permissions-faq/
Explore Training at:
https://www.scaledagile.com/training/calendar/

**Comment by debsmith-ux** [comment]
As a (user role), I want to (activity), so that (business value)

© Scaled Agile, Inc.
Include this copyright notice with the copied content.

Read the FAQs on how to use SAFe content and trademarks here:
https://www.scaledagile.com/about/about-us/permissions-faq/
Explore Training at:
https://www.scaledagile.com/training/calendar/

**Comment by debsmith-ux** [comment]
Invest in Good Stories The INVEST model, developed by Bill Wake [1], describes characteristics of good user stories:  I – Independent (among other stories) N – Negotiable (a flexible statement of intent, not a contract) V – Valuable (providing a valuable vertical slice to the customer) E – Estimable (small and negotiable) S – Small (fits within an iteration) T – Testable (understood enough to know how to test it)

© Scaled Agile, Inc.
Include this copyright notice with the copied content.

Read the FAQs on how to use SAFe content and trademarks here:
https://www.scaledagile.com/about/about-us/permissions-faq/
Explore Training at:
https://www.scaledagile.com/training/calendar/

**Comment by debsmith-ux** [comment]
Because stories let you focus on building small things, it’s easy to lose sight of the big picture. The result is often a “Franken-product” where it’s clear to everyone using the product that it’s assembled from mismatched parts.
When you’re building a product of any significant size, building one small thing after another leaves people wondering when you’ll ever be done, or what exactly you’ll deliver. If you’re the builder, you wonder, too.
Because stories are about conversations, people use that idea to avoid writing anything down. Then they forget what they talked about and agreed to in the conversations.
Because good stories are supposed to have acceptance criteria, we focus on getting acceptance criteria written, but there’s still not a common understanding of what needs to be built. As a consequence, teams don’t finish the work they plan on in the timeframe they planned to.
Because good stories are supposed to be written from a user’s perspective, and there are lots of parts that users never see, team members argue that "our product doesn’t have users, so user stories won’t work here."

**Comment by debsmith-ux** [comment]
Definition of Ready means that the User Story can be worked on, it is ready to be worked on.

Definition of Ready for a user story:

Well-defined User story according to template
User story acceptance criteria defined clearly
System Analyst and User Experience (UX) have been consulted
It is vertically sliced user story and can be demoed with test doubles or otherwise
User story sized by the Agile team
Performance and security criteria has been identified if applicable

**Comment by debsmith-ux** [comment]
Figure 2. Example user story in user voice form ‘Personas’ describe specific characteristics of representative users that help teams better understand their end user.  Example personas for the rider in Figure 2 could be a thrill-seeker ‘Jane’ and a timid rider ‘Bob’. Stories descriptions then reference these personas (As Jane I want…). While the user story voice is the common case, not every system interacts with an end user. Sometimes the ‘user’ is a device (e.g., printer) or a system (e.g., transaction server). In these cases, the story can take on the form illustrated in Figure 3.

© Scaled Agile, Inc.
Include this copyright notice with the copied content.

Read the FAQs on how to use SAFe content and trademarks here:
https://www.scaledagile.com/about/about-us/permissions-faq/
Explore Training at:
https://www.scaledagile.com/training/calendar/

**Comment by debsmith-ux** [comment]
User Story DoD Examples:

o   Unit tests passed

o   Code reviewed

o   Acceptance criteria met

o   Functional tests passed

o   Non-Functional requirements met

o   Product Owner accepts the User Story
